/**
 * Vehicle Type Definition
 * Represents a vehicle in the AutoVentas Premium catalog
 */
export interface Vehicle {
  id: string;
  brand: string;
  model: string;
  price: number;
  year: number;
  image: string;
  description: string;
}

/**
 * Type for creating a new vehicle (without ID)
 * ID will be auto-generated by the context
 */
export type CreateVehicleInput = Omit<Vehicle, 'id'>;

/**
 * Type for updating an existing vehicle
 * All fields are optional except ID
 */
export type UpdateVehicleInput = Partial<Omit<Vehicle, 'id'>>;
